name: Terraform Apply

on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string
      module_directory:
        required: true
        type: string
    secrets:
      azure_client_id:
        required: true
        description: 'Azure Client ID for authentication'
      azure_client_secret:
        required: true
        description: 'Azure Client Secret for authentication'
      azure_tenant_id:
        required: true
        description: 'Azure Tenant ID for authentication'
      azure_subscription_id:
        required: true
        description: 'Azure Subscription ID for identification'

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    # Define environment variables at the job level
    env:
      ARM_CLIENT_ID: ${{ secrets.azure_client_id }}
      ARM_CLIENT_SECRET: ${{ secrets.azure_client_secret }}
      ARM_TENANT_ID: ${{ secrets.azure_tenant_id }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.azure_subscription_id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "${{ inputs.terraform_version }}"

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ${{ inputs.module_directory }}

      - name: Terraform Apply
        run: |
          cd ${{ inputs.module_directory }}
          terraform apply tfplan
          