name: Terraform Destroy Workflow

on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string
      terraform_directory:
        required: true
        type: string

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "${{ inputs.terraform_version }}"

      - name: Terraform Initialization
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
          az account set --subscription $ARM_SUBSCRIPTION_ID
          
          cd ${{ inputs.terraform_directory }}
          terraform init -upgrade

      - name: Terraform Validate
        run: |
          cd ${{ inputs.terraform_directory }}
          terraform validate

      - name: Terraform Destroy Plan
        run: |
          cd ${{ inputs.terraform_directory }}
          terraform plan -destroy -out=destroy.tfplan

      - name: Save Destroy Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-destroy-plan
          path: ${{ inputs.terraform_directory }}/destroy.tfplan

      - name: Terraform Destroy
        run: |
          cd ${{ inputs.terraform_directory }}
          terraform apply destroy.tfplan
