name: Terraform Apply Template

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "${{ inputs.terraform_version }}"

    - name: Download Terraform Plan
      uses: actions/download-artifact@v4
      with:
        name: terraform-plan
        path: ${{ inputs.terraform_directory }}

    - name: Manual Approval
      uses: hmarr/auto-approve-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Terraform Apply
      run: |
        cd ${{ inputs.terraform_directory }}
        terraform apply tfplan